### ISSUE TITLE
Set supported natively by language in Swift v1.2

### ISSUE THREAD

**Issue by ankurp** [robrix/Set#45] opened 2015-02-09 19:39 UTC
New native Set data structure — An unordered collection of unique elements that bridges with NSSet and provides value semantics like Array and Dictionary.

https://developer.apple.com/swift/blog/?id=22

**Comment by robrix** [comment] 2015-02-09 19:44
Duplicate of #44.

**Closed by robrix** 2015-02-09 19:44 UTC
